

export const AXIS_HEIGHT = 200;

const MARGIN_LEFT = 25;
const MARGIN_TOP = 25;
const MARGIN_RIGHT = 25;
const MARGIN_BOTTOM = 25;

export const MARGINS = { LEFT: MARGIN_LEFT, TOP: MARGIN_TOP, RIGHT: MARGIN_RIGHT, BOTTOM: MARGIN_BOTTOM };

export const PLOT_WIDTH = 2*AXIS_HEIGHT;
export const PLOT_HEIGHT = 2*AXIS_HEIGHT;

export const PLOT_AREA_WIDTH = PLOT_WIDTH + MARGIN_LEFT + MARGIN_RIGHT;
export const PLOT_AREA_HEIGHT = PLOT_HEIGHT + MARGIN_LEFT + MARGIN_RIGHT;
